name: Build Status

on: 
  push:
    branches: [ "cristina/ci-cd-action" ]
  pull_request:
    branches: [ "cristina/ci-cd-action" ]
  # workflow_dispatch:

jobs:
  push-ADXUTILS:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run
      run:  dotnet run --project /home/runner/work/AdxUtils/AdxUtils/AdxUtils.Cli/AdxUtils.Cli.csproj --database eis-dev-db-01 --i adt_dh_eis_dev_twin_01_westeurope --e Permission,colorization_rules --client-id ${{ secrets.ADX_CLIENT_ID }} --client-secret ${{ secrets.ADX_CLIENT_SECRET }} --c ${{ secrets.ADX_URI }} --authority ${{ secrets.ADX_TENANT_ID }}


    
   
